# Generated by Django 4.2 on 2023-04-09 13:11

from django.db import migrations, models
import django.db.models.deletion
import real_estate_card.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=255, verbose_name='округ')),
                ('district', models.CharField(max_length=255, verbose_name='район')),
                ('address', models.CharField(max_length=255, verbose_name='адрес')),
                ('type', models.CharField(max_length=255, verbose_name='тип')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='описание')),
                ('state', models.CharField(choices=[('new', 'новый'), ('process', 'в работе'), ('finish', 'завершен')], default='new', max_length=255, verbose_name='состояние')),
                ('square', models.FloatField(verbose_name='площадь (кв.м.)')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.CreateModel(
            name='RealEstateActualUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='фамилия')),
                ('surname', models.CharField(max_length=255, verbose_name='отчество')),
            ],
            options={
                'verbose_name': 'Фактиечский пользовтаель',
                'verbose_name_plural': 'Фактические пользователи',
            },
        ),
        migrations.CreateModel(
            name='RealEstateOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='фамилия')),
                ('surname', models.CharField(max_length=255, verbose_name='отчество')),
                ('passport', models.CharField(max_length=10, unique=True, verbose_name='паспорт')),
            ],
            options={
                'verbose_name': 'Владелец',
                'verbose_name_plural': 'Владельцы',
            },
        ),
        migrations.CreateModel(
            name='RealEstatePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='название')),
                ('image', models.ImageField(upload_to=real_estate_card.models.media_dir_path, verbose_name='фотография')),
                ('real_estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate_card.realestate', verbose_name='объект')),
            ],
            options={
                'verbose_name': 'Фото объектов',
                'verbose_name_plural': 'Фото объектов',
            },
        ),
        migrations.AddField(
            model_name='realestate',
            name='actual_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='real_estate_card.realestateactualuser', verbose_name='фактический пользователь'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='real_estate_card.realestateowner', verbose_name='владелец'),
        ),
    ]
