# Generated by Django 4.2 on 2023-04-09 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('real_estate_card', '0001_initial'),
        ('users', '0001_initial'),
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutions',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.group', verbose_name='группа'),
        ),
        migrations.AddField(
            model_name='solutions',
            name='real_estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='real_estate_card.realestate', verbose_name='объекты'),
        ),
        migrations.AddField(
            model_name='question',
            name='real_estate',
            field=models.ManyToManyField(to='real_estate_card.realestate', verbose_name='объекты'),
        ),
    ]
